# in .github/workflows/continuous_deployment.yml
name: Continuous deployment
on:
  push:
    paths:
      - 'dist/**'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
